name: advocateoffice
description: "This project is developed to manage the Advocate Office Management System."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  connectivity_plus: ^6.1.0
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^27.2.5
  fl_chart: ^0.69.2
  intl: ^0.19.0
  data_table_2: ^2.5.16
  syncfusion_flutter_datepicker: ^27.2.5
  gap: ^3.0.1
  lottie: ^3.1.3
  widget_zoom: ^0.0.4
  super_drag_and_drop: ^0.8.24
  file_picker: ^8.1.4
  flutter_dropzone: ^4.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  syncfusion_flutter_pdf: ^27.2.2
  path_provider: ^2.0.11
  open_file: ^3.2.1
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.2.2
  textfield_tags: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/advocate.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/advocate.png"
  windows:
    generate: true
    image_path: "assets/advocate.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/advocate.png"


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/animations/